Update h5ad-to-arrow dependencies (#27)
* h5ad_to_arrow: bump anndata to 0.7.1, h5ad to 2.10.0

Properly fixes this:

"""
Traceback (most recent call last):
  File "/main.py", line 67, in <module>
    main(args.input_dir, args.output_dir)
  File "/main.py", line 50, in main
    h5ad_to_arrow(input_path, arrow_path)
  File "/main.py", line 13, in h5ad_to_arrow
    ann_data = read_h5ad(h5ad_file)
  File "/opt/conda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 447, in read_h5ad
    constructor_args = _read_args_from_h5ad(filename=filename, chunk_size=chunk_size)
  File "/opt/conda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 486, in _read_args_from_h5ad
    _read_key_value_from_h5(f, d, key, chunk_size=chunk_size)
  File "/opt/conda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 510, in _read_key_value_from_h5
    _read_key_value_from_h5(f, d[key_write], key + '/' + k, k, chunk_size)
  File "/opt/conda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 510, in _read_key_value_from_h5
    _read_key_value_from_h5(f, d[key_write], key + '/' + k, k, chunk_size)
  File "/opt/conda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 544, in _read_key_value_from_h5
    key, value = postprocess_reading(key, value)
  File "/opt/conda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 541, in postprocess_reading
    value = value.astype(new_dtype)
ValueError: invalid shape in fixed-type tuple.
"""

* Ignore .idea/ (PyCharm project directory)

* h5ad-to-arrow.cwl: bump container version to new 0.0.2

In a conversation with Ilan just now, he said that I should tag and push a
new container with updated dependencies. As a bonus, this will hopefully
cause the Travis build to succeed now that the dependencies match what's in
`requirements-freeze.txt`.

* h5ad-to-arrow/.../requirements-freeze.txt: Add new auto-pulled packages